name: Build and Push Docker Image for Prepare

on:
  push:
    paths:
      - 'cmd/prepare/main.go'
      - 'Dockerfile.prepare'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t gregbaker/ultratree-prepare -f Dockerfile.prepare .

    - name: Push Docker image
      run: docker push gregbaker/ultratree-prepare
