name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Check and create mock SQLite files
      run: |
        if [ ! -f /tinystories/wordnetify-tinystories/TinyStories.sqlite ]; then
          echo "Creating mock TinyStories.sqlite"
          mkdir -p /tinystories/wordnetify-tinystories
          sqlite3 /tinystories/wordnetify-tinystories/TinyStories.sqlite "VACUUM;"
        fi
        if [ ! -f /tinystories/wordnetify-tinystories/w2.sqlite ]; then
          echo "Creating mock w2.sqlite"
          mkdir -p /tinystories/wordnetify-tinystories
          sqlite3 /tinystories/wordnetify-tinystories/w2.sqlite "VACUUM;"
        fi

    - name: Build
      run: make
